spring:
  application:
    name: gate

  datasource:
    url: JDBC:postgresql://localhost:5444/nl2sql
    username: app
    password: app
    driver-class-name: org.postgresql.Driver

  # 터미널에 sql보여주기 및 정렬 용도
  jpa:
    hibernate:
      ddl-auto: none #JPA가 테이블을 건드리지 않음
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.0

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.nl2sql.gate: DEBUG